export default interface WorkorderStateInterface {
    objWorkorder?:any;
    loader?:boolean;
    serachText?:any;
    objStatus?:any;
    selectedFilter?:any;
    location?:any;
    user?:any;
    curTime?:any;
    intervalId?:any;
    curDate?:any;
    isStarted?:boolean;
    timeLine?:any;
    isAnyJobStarted?:boolean,
    clockedInStartTime?:any,
    clockInId?:number,
    work_order_id?:number,
    selectedStartDate?:any,
    minDate?:any,
    navigation?:any,
    objData?:any,
    objSlot?:any,
    objSlotKey?:any,
    selectedSlot?:any,
    maxDate?:any,
}